### ISSUE TITLE
Arrays from Window Object

### ISSUE THREAD

**Issue by ravilution** [danielpa9708/parcel-globals#1]
```sh
./node_modules/.bin/parcel-globals @material-ui/core window['material-ui']
```
Got this error `zsh: no matches found: window[material-ui]`

Even when it failed. It added below entry into `package.json`

```javascript
"@material-ui/core": ".parcel-globals/@material-ui/core.js"
```

**Comment by danielpa9708** [comment]
Thanks for submitting the issue, I'll check it out and fix it soon I hope

**Comment by danielpa9708** [comment]
I think is a problem with zsh, I test it with bash and it returned no errors

**Comment by danielpa9708** [comment]
Haven't publish the fix due to 

```Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".```

I let you know when it is done

**Comment by danielpa9708** [comment]
You should be able to install it now, `+ parcel-globals@0.2.2`

**Comment by danielpa9708** [comment]
@ravilution this is an issue with zsh, I tried it with bash and it worked just fined, sorry for closing the issue, there was also an issue when the packages were scoped like `@material-ui/core` and I mistake it with this

**Comment by danielpa9708** [comment]
You'll need to surround it with " like this `./node_modules/.bin/parcel-globals @material-ui/core "window['material-ui']"`

**Comment by ravilution** [comment]
With `0.2.2` below command worked fine. Thank you for fixing.
`./node_modules/.bin/parcel-globals @material-ui/core "window['material-ui']"`
